import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
import { readFileSync } from 'node:fs'
import path from 'node:path'

/**
 * Build config for `npm run publish`. Renders — and bundles — only a single deck.
 *
 * Driven by env vars set by scripts/publish.mjs:
 *   VITE_PUBLISH_DECK   the deck name (also baked into the bundle)
 *   PUBLISH_OUT_DIR     output directory, e.g. dist/publish/<deck>
 *
 * SECURITY: the normal app discovers decks/slides with `import.meta.glob`, which
 * matches EVERY deck in the repo. If we reused that for publishing, the public
 * static bundle would contain every other deck's compiled slides — a data leak.
 * The `restrictToPublishedDeck` plugin below replaces the two registry modules
 * (src/lib/decks.ts, src/lib/slides.ts) with generated versions scoped to just
 * the published deck, so nothing else is ever bundled.
 */

const ROOT = __dirname

interface RawDeck {
  title: string
  description?: string
  author?: string
  createdAt?: string
  slides: string[]
}

/** shared slide → "shared"; deck-local → its deck name. Mirrors src/lib/slides.ts. */
function classify(p: string): { scope: string; name: string } {
  if (p.startsWith('slides/')) {
    return { scope: 'shared', name: p.replace(/^slides\//, '').replace(/\.tsx$/, '') }
  }
  const m = p.match(/^decks\/([^/]+)\/slides\/(.+)\.tsx$/)
  if (m) return { scope: m[1], name: m[2] }
  throw new Error(`[publish] unrecognized slide path in manifest: ${p}`)
}

function restrictToPublishedDeck(deckName: string): Plugin {
  const manifest: RawDeck = JSON.parse(
    readFileSync(path.resolve(ROOT, 'decks', deckName, 'deck.json'), 'utf8'),
  )
  const slides = Array.isArray(manifest.slides) ? manifest.slides : []

  const decksModule = `// generated by vite.publish.config.ts — scoped to "${deckName}"
const deck = {
  name: ${JSON.stringify(deckName)},
  manifestPath: ${JSON.stringify(`decks/${deckName}/deck.json`)},
  title: ${JSON.stringify(manifest.title)},
  description: ${JSON.stringify(manifest.description)},
  author: ${JSON.stringify(manifest.author)},
  createdAt: ${JSON.stringify(manifest.createdAt)},
  slides: ${JSON.stringify(slides)},
}
export const allDecks = [deck]
const byName = new Map(allDecks.map((d) => [d.name, d]))
export function getDeck(name) { return byName.get(name) }
`

  const records = slides.map((p) => {
    const { scope, name } = classify(p)
    // Static string-literal import() so Rollup bundles ONLY these slides.
    return `  { path: ${JSON.stringify(p)}, scope: ${JSON.stringify(scope)}, name: ${JSON.stringify(
      name,
    )}, load: () => import(${JSON.stringify('/' + p)}) }`
  })

  const slidesModule = `// generated by vite.publish.config.ts — scoped to "${deckName}"
export const allSlides = [
${records.join(',\n')}
]
const byPath = new Map(allSlides.map((s) => [s.path, s]))
export function getSlide(path) { return byPath.get(path) }
export function sharedSlides() { return allSlides.filter((s) => s.scope === 'shared') }
export function deckLocalSlides(deckName) { return allSlides.filter((s) => s.scope === deckName) }
`

  const ROOT_POSIX = ROOT.replace(/\\/g, '/')
  const DECKS = path.resolve(ROOT, 'src/lib/decks.ts').replace(/\\/g, '/')
  const SLIDES = path.resolve(ROOT, 'src/lib/slides.ts').replace(/\\/g, '/')
  const PUBLISHED = path.resolve(ROOT, 'src/lib/published.ts').replace(/\\/g, '/')

  // published.ts statically imports the whole .pagecast/published.json (every
  // deck's URL + publisher email). It isn't in the publish render graph today,
  // but stub it so cross-deck publication data can never enter a public bundle
  // even if some component starts importing it.
  const publishedStub = `// generated by vite.publish.config.ts — neutralized for publish
export function getPublished() { return undefined }
export function allPublished() { return {} }
`

  // A slide source file is `slides/**/*.tsx` or `decks/<name>/slides/*.tsx`.
  const isSlideFile = (rel: string) =>
    /^slides\/.+\.tsx$/.test(rel) || /^decks\/[^/]+\/slides\/.+\.tsx$/.test(rel)

  // Does the file declare a `notes` export at all? (cheap gate before the heavier match)
  const HAS_NOTES = /\bexport\s+const\s+notes\b/
  // Matches `export const notes = <ONE string/template literal>` ONLY when that
  // literal is the whole initializer — the trailing lookahead requires a new
  // statement to follow, so a concatenation/interpolation/reference won't match
  // and the build fails closed rather than leaking a partial value.
  const NOTES_DECL =
    /export\s+const\s+notes\s*=\s*(['"`])(?:\\.|(?!\1)[\s\S])*?\1\s*;?(?=\s*(?:$|[\r\n]|export|import|const|let|var|function|class))/

  return {
    name: 'pagecast:restrict-to-published-deck',
    enforce: 'pre',
    load(id) {
      const clean = id.split('?')[0].replace(/\\/g, '/')
      if (clean === DECKS) return decksModule
      if (clean === SLIDES) return slidesModule
      if (clean === PUBLISHED) return publishedStub
      // Isolation guard: refuse to bundle ANY file belonging to another deck.
      // Rollup follows imports transitively, so without this a slide that
      // imports `../../other-deck/slides/secret` would pull that deck into the
      // public output. Shared slides (`/slides/**`) and the published deck's own
      // files are allowed; everything else under `/decks/<other>/` is blocked.
      if (clean.startsWith(ROOT_POSIX + '/decks/')) {
        const m = clean.slice(ROOT_POSIX.length + 1).match(/^decks\/([^/]+)\//)
        if (m && m[1] !== deckName) {
          this.error(
            `[publish] refusing to bundle "${m[0]}…" — it belongs to deck "${m[1]}", not ` +
              `the published deck "${deckName}". A slide in "${deckName}" must not import another deck's files.`,
          )
        }
      }
      return null
    },
    transform(code, id) {
      // Speaker notes are private — strip them from published slide bundles so
      // they never reach the public site. (Export/dev keep them; the PDF never
      // renders them.) We only strip a notes export whose value is a single
      // string/template literal. Anything else (concatenation, interpolation, a
      // reference to a variable) we CANNOT safely neutralize with a text edit, so
      // we FAIL the build rather than risk leaking part of the value.
      const clean = id.split('?')[0].replace(/\\/g, '/')
      if (!clean.startsWith(ROOT_POSIX + '/')) return null
      const rel = clean.slice(ROOT_POSIX.length + 1)
      if (!isSlideFile(rel) || !HAS_NOTES.test(code)) return null

      if (!NOTES_DECL.test(code)) {
        this.error(
          `[publish] notes in ${rel} is not a single string literal, so it can't be safely ` +
            `stripped for publishing. Make it one plain string (or remove it) — otherwise its ` +
            `contents could leak into the public bundle.`,
        )
      }
      return { code: code.replace(NOTES_DECL, 'export const notes = "";'), map: null }
    },
  }
}

const publishDeck = process.env.VITE_PUBLISH_DECK
if (!publishDeck) {
  throw new Error('VITE_PUBLISH_DECK is required for the publish build (set by scripts/publish.mjs)')
}

export default defineConfig({
  plugins: [restrictToPublishedDeck(publishDeck), react()],
  base: './',
  resolve: {
    alias: { '@': path.resolve(ROOT, 'src') },
  },
  build: {
    outDir: process.env.PUBLISH_OUT_DIR || 'dist/publish/unknown',
    emptyOutDir: true,
    rollupOptions: {
      input: path.resolve(ROOT, 'publish.html'),
    },
  },
})
